#!/usr/bin/env bash
#
# STT Service Installer
# Installs WhisperLive Docker service with systemd integration
#
# Usage:
#   ./install.sh [OPTIONS]
#
# Options:
#   --model MODEL      Whisper model (tiny, base, small, medium, large-v2, large-v3)
#   --language LANG    Default language code (en, es, fr, etc.)
#   --port PORT        Service port (default: 9090)
#   --uninstall        Remove the service
#   --help             Show this help
#
# Requires: sudo, docker, docker-compose-plugin, NVIDIA GPU

set -euo pipefail

# Default configuration
WHISPER_MODEL="${WHISPER_MODEL:-small}"
WHISPER_LANGUAGE="${WHISPER_LANGUAGE:-en}"
STT_PORT="${STT_PORT:-9090}"

# Installation paths
INSTALL_DIR="${HOME}/.automation/stt"
SERVICE_NAME="automation-stt"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

show_help() {
    head -20 "$0" | tail -15 | sed 's/^# //' | sed 's/^#//'
    exit 0
}

check_requirements() {
    log_info "Checking requirements..."
    
    local missing=()
    
    command -v docker &>/dev/null || missing+=("docker")
    docker compose version &>/dev/null || missing+=("docker-compose-plugin")
    
    if [[ ${#missing[@]} -gt 0 ]]; then
        log_error "Missing requirements: ${missing[*]}"
        log_info "Install with: sudo apt install docker.io docker-compose-plugin"
        exit 1
    fi
    
    if ! docker info &>/dev/null; then
        log_error "Docker daemon not running or permission denied"
        log_info "Try: sudo systemctl start docker && sudo usermod -aG docker $USER"
        exit 1
    fi
    
    # Check NVIDIA GPU
    if ! command -v nvidia-smi &>/dev/null; then
        log_warn "nvidia-smi not found - GPU acceleration may not work"
    fi
    
    log_success "All requirements met"
}

create_compose_file() {
    log_info "Creating compose configuration in ${INSTALL_DIR}..."
    
    mkdir -p "${INSTALL_DIR}/models"
    
    cat > "${INSTALL_DIR}/compose.yml" << EOF
# CodeWhisper WhisperLive STT Service
# Auto-generated by install.sh

services:
  stt:
    image: ghcr.io/collabora/whisperlive-gpu:latest
    container_name: stt
    ports:
      - "${STT_PORT}:9090"
    volumes:
      - ./models:/root/.cache/huggingface
    environment:
      - WHISPER_MODEL=${WHISPER_MODEL}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.connect(('localhost', 9090)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
EOF
    
    log_success "Compose file created"
}

create_systemd_service() {
    log_info "Creating systemd service..."
    
    local service_content
    service_content=$(cat << EOF
[Unit]
Description=CodeWhisper WhisperLive STT Service
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
User=${USER}
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
ExecReload=/usr/bin/docker compose restart
TimeoutStartSec=180
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
EOF
)
    
    echo "$service_content" | sudo tee "${SERVICE_FILE}" > /dev/null
    
    sudo systemctl daemon-reload
    log_success "Systemd service created"
}

enable_service() {
    log_info "Enabling and starting service..."
    
    sudo systemctl enable "${SERVICE_NAME}"
    sudo systemctl start "${SERVICE_NAME}"
    
    log_info "Waiting for service to be ready (model download may take a while)..."
    sleep 10
    
    if sudo systemctl is-active --quiet "${SERVICE_NAME}"; then
        log_success "Service is running"
    else
        log_warn "Service may still be starting (model download in progress)"
        log_info "Check status with: systemctl status ${SERVICE_NAME}"
    fi
}

uninstall_service() {
    log_info "Uninstalling ${SERVICE_NAME}..."
    
    if systemctl is-active --quiet "${SERVICE_NAME}" 2>/dev/null; then
        sudo systemctl stop "${SERVICE_NAME}"
    fi
    
    if systemctl is-enabled --quiet "${SERVICE_NAME}" 2>/dev/null; then
        sudo systemctl disable "${SERVICE_NAME}"
    fi
    
    if [[ -f "${SERVICE_FILE}" ]]; then
        sudo rm "${SERVICE_FILE}"
        sudo systemctl daemon-reload
    fi
    
    log_success "Service uninstalled"
    log_info "Data directory preserved at: ${INSTALL_DIR}"
    log_info "To remove data: rm -rf ${INSTALL_DIR}"
}

show_status() {
    echo ""
    log_info "Installation complete!"
    echo ""
    echo "Configuration:"
    echo "  Model:    ${WHISPER_MODEL}"
    echo "  Language: ${WHISPER_LANGUAGE} (set in client)"
    echo "  Port:     ${STT_PORT}"
    echo ""
    echo "Service commands:"
    echo "  Status:   systemctl status ${SERVICE_NAME}"
    echo "  Start:    sudo systemctl start ${SERVICE_NAME}"
    echo "  Stop:     sudo systemctl stop ${SERVICE_NAME}"
    echo "  Restart:  sudo systemctl restart ${SERVICE_NAME}"
    echo "  Logs:     docker logs -f stt"
    echo ""
    echo "Test connection:"
    echo "  python -c \"import socket; s=socket.socket(); s.connect(('localhost', ${STT_PORT})); print('OK'); s.close()\""
    echo ""
    echo "VS Code/Cursor settings:"
    echo "  codewhisper.whisperEndpoint: ws://localhost:${STT_PORT}"
    echo "  codewhisper.whisperModel: ${WHISPER_MODEL}"
    echo "  codewhisper.whisperLanguage: ${WHISPER_LANGUAGE}"
    echo ""
}

main() {
    local action="install"
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            --model)
                WHISPER_MODEL="$2"
                shift 2
                ;;
            --language)
                WHISPER_LANGUAGE="$2"
                shift 2
                ;;
            --port)
                STT_PORT="$2"
                shift 2
                ;;
            --uninstall)
                action="uninstall"
                shift
                ;;
            --help|-h)
                show_help
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                ;;
        esac
    done
    
    if [[ "$action" == "uninstall" ]]; then
        uninstall_service
        exit 0
    fi
    
    check_requirements
    create_compose_file
    create_systemd_service
    enable_service
    show_status
}

main "$@"
